### ISSUE TITLE
The accuracy of the dynamic target segmentation

### ISSUE THREAD

**Issue by Shengqi77** [Riponcs/Turb-Seg-Res#2]
Hello! I have some concerns about the accuracy of the dynamic target segmentation in your method, specifically regarding the mask accuracy. I tried running the single_car case and saved the intermediate segmentation mask results. The mask for the first frame of the target, as shown in the below image (Figure 2), seems to be quite inaccurate compared to the masks provided in the dataset or the published article (Figure 3).

![FG](https://github.com/user-attachments/assets/d7a3f848-5909-4935-918c-228e9c5ed92c)
![mask](https://github.com/user-attachments/assets/be2b6e61-d6d2-43c4-ac32-4b2b09106ff4)
![00000](https://github.com/user-attachments/assets/ed1cb9fe-31e5-4c40-b7cd-65c72ec06e70)

**Comment by Riponcs** [comment]
I guess you are using Masks variable (which is already dialated), instead of GlobalSegMaskList.
To get the model's predicted mask, use a thin line on Demo 36 (line), and it will solve the problem: `plt.imshow(GlobalSegMaskList[0], cmap='gray'), plt.axis('off'), plt.show()`
![image](https://github.com/user-attachments/assets/8b63d3ed-d512-41e9-80e5-01ec1b7cc07f)

The reason you see these large mask is that we intentionally added large padding on the object boundary to address the issue with shadows and smearing artifacts in the video.
